databases:
  - name: spotlight_DB
    databaseName: spotlight_db
    user: spotlight
    region: singapore

services:
  - type: web
    name: spotlight
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: spotlight_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false